version: '3'
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on: 
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=MyRightHand
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres_data: